apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "7"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"cattle-node-agent","namespace":"cattle-system"},"spec":{"selector":{"matchLabels":{"app":"cattle-agent"}},"template":{"metadata":{"labels":{"app":"cattle-agent"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/os","operator":"NotIn","values":["windows"]}]}]}}},"containers":[{"env":[{"name":"CATTLE_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"CATTLE_SERVER","value":"https://rancher-prod.doubleverify.io"},{"name":"CATTLE_CA_CHECKSUM","value":""},{"name":"CATTLE_CLUSTER","value":"false"},{"name":"CATTLE_K8S_MANAGED","value":"true"},{"name":"CATTLE_AGENT_CONNECT","value":"true"}],"image":"rancher/rancher-agent:v2.5.3","imagePullPolicy":"IfNotPresent","name":"agent","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/cattle-credentials","name":"cattle-credentials","readOnly":true},{"mountPath":"/etc/kubernetes","name":"k8s-ssl"},{"mountPath":"/var/run","mountPropagation":"HostToContainer","name":"var-run"},{"mountPath":"/run","mountPropagation":"HostToContainer","name":"run"},{"mountPath":"/etc/docker/certs.d","name":"docker-certs"}]}],"hostNetwork":true,"serviceAccountName":"cattle","tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/etc/kubernetes","type":"DirectoryOrCreate"},"name":"k8s-ssl"},{"hostPath":{"path":"/var/run","type":"DirectoryOrCreate"},"name":"var-run"},{"hostPath":{"path":"/run","type":"DirectoryOrCreate"},"name":"run"},{"name":"cattle-credentials","secret":{"defaultMode":320,"secretName":"cattle-credentials-111538d"}},{"hostPath":{"path":"/etc/docker/certs.d","type":"DirectoryOrCreate"},"name":"docker-certs"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"25%"},"type":"RollingUpdate"}}}
    creationTimestamp: "2019-11-14T14:01:04Z"
    generation: 7
    labels:
      app: cattle-agent
    name: cattle-node-agent
    namespace: cattle-system
    resourceVersion: "338253322"
    selfLink: /apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent
    uid: 26e3f500-406b-4405-b647-bd5d4249a1bc
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: cattle-agent
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cattle-agent
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/os
                  operator: NotIn
                  values:
                  - windows
        containers:
        - env:
          - name: CATTLE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: CATTLE_SERVER
            value: https://rancher-prod.doubleverify.io
          - name: CATTLE_CA_CHECKSUM
          - name: CATTLE_CLUSTER
            value: "false"
          - name: CATTLE_K8S_MANAGED
            value: "true"
          - name: CATTLE_AGENT_CONNECT
            value: "true"
          image: rancher/rancher-agent:v2.5.3
          imagePullPolicy: IfNotPresent
          name: agent
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /cattle-credentials
            name: cattle-credentials
            readOnly: true
          - mountPath: /etc/kubernetes
            name: k8s-ssl
          - mountPath: /var/run
            mountPropagation: HostToContainer
            name: var-run
          - mountPath: /run
            mountPropagation: HostToContainer
            name: run
          - mountPath: /etc/docker/certs.d
            name: docker-certs
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: cattle
        serviceAccountName: cattle
        terminationGracePeriodSeconds: 30
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /etc/kubernetes
            type: DirectoryOrCreate
          name: k8s-ssl
        - hostPath:
            path: /var/run
            type: DirectoryOrCreate
          name: var-run
        - hostPath:
            path: /run
            type: DirectoryOrCreate
          name: run
        - name: cattle-credentials
          secret:
            defaultMode: 320
            secretName: cattle-credentials-111538d
        - hostPath:
            path: /etc/docker/certs.d
            type: DirectoryOrCreate
          name: docker-certs
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 25%
      type: RollingUpdate
  status:
    currentNumberScheduled: 11
    desiredNumberScheduled: 11
    numberAvailable: 11
    numberMisscheduled: 0
    numberReady: 11
    observedGeneration: 7
    updatedNumberScheduled: 11
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"kube-api-auth","namespace":"cattle-system"},"spec":{"selector":{"matchLabels":{"app":"kube-api-auth"}},"template":{"metadata":{"labels":{"app":"kube-api-auth"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/os","operator":"NotIn","values":["windows"]},{"key":"node-role.kubernetes.io/controlplane","operator":"In","values":["true"]}]}]}}},"containers":[{"image":"rancher/kube-api-auth:v0.1.4","imagePullPolicy":"IfNotPresent","name":"kube-api-auth","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/etc/kubernetes","name":"k8s-ssl"}]}],"hostNetwork":true,"serviceAccountName":"cattle","tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/etc/kubernetes","type":"DirectoryOrCreate"},"name":"k8s-ssl"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"25%"},"type":"RollingUpdate"}}}
    creationTimestamp: "2019-11-14T14:01:04Z"
    generation: 3
    name: kube-api-auth
    namespace: cattle-system
    resourceVersion: "338253252"
    selfLink: /apis/apps/v1/namespaces/cattle-system/daemonsets/kube-api-auth
    uid: 90c4150b-28c8-4d90-bfda-6fafa59d4144
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: kube-api-auth
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: kube-api-auth
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/os
                  operator: NotIn
                  values:
                  - windows
                - key: node-role.kubernetes.io/controlplane
                  operator: In
                  values:
                  - "true"
        containers:
        - image: rancher/kube-api-auth:v0.1.4
          imagePullPolicy: IfNotPresent
          name: kube-api-auth
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/kubernetes
            name: k8s-ssl
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: cattle
        serviceAccountName: cattle
        terminationGracePeriodSeconds: 30
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /etc/kubernetes
            type: DirectoryOrCreate
          name: k8s-ssl
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 25%
      type: RollingUpdate
  status:
    currentNumberScheduled: 3
    desiredNumberScheduled: 3
    numberAvailable: 3
    numberMisscheduled: 0
    numberReady: 3
    observedGeneration: 3
    updatedNumberScheduled: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
