{{- if (include "additional-scrape-configs.yaml" .) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}-additional-scrape-configs
stringData:
  additional-scrape-configs.yaml: {{ template "additional-scrape-configs.yaml" . }}
{{- end }}

{{- if (include "additional-alertmanager-configs.yaml" .) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}-additional-alertmanager-configs
stringData:
  additional-alertmanager-configs.yaml: {{ template "additional-alertmanager-configs.yaml" . }}
{{- end }}

{{- if .Values.thanos.enabled }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.thanos.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
stringData:
{{- if .Values.thanos.gcs_config }}
  thanos.yaml: |-
    config:
      bucket: {{ .Values.thanos.gcs_config.bucket }}
      type: GCS
      service_account: |-
        {
          "type": "service_account",
          "project_id": {{ quote .Values.thanos.gcs_config.project_id }},
          "private_key_id": {{ quote .Values.thanos.gcs_config.private_key_id }},
          "private_key": {{ quote .Values.thanos.gcs_config.private_key }},
          "client_email": {{ quote .Values.thanos.gcs_config.client_email }},
          "client_id": {{ quote .Values.thanos.gcs_config.client_id }},
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": {{ quote .Values.thanos.gcs_config.client_x509_cert_url }}
        }
{{- else }}
  thanos.yaml: |-
{{ toJson .Values.thanos.objectConfig | indent 6 }}
{{- end }}
{{- end }}
