apiVersion: v1
kind: Service
metadata:
  name: access-prometheus
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
    - name: nginx-http
      port: 80
      targetPort: nginx-http

{{- if .Values.thanos.enabled }} 
---
apiVersion: v1
kind: Service
metadata:
  name: access-thanos
  annotations:
    cloud.google.com/load-balancer-type: Internal
    {{- if .Values.thanos.annotations }}
    {{- toYaml .Values.thanos.annotations | nindent 4 }}
    {{- end }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
    - name: thanos-grpc
      port: 10901
      targetPort: 10901
    - name: thanos-http
      port: 10902
      targetPort: 10902
{{- end }}
